### ISSUE TITLE
It's impossible to set two different asset on the same issuing address

### ISSUE THREAD

**Issue by skraba** [ety001/stellar-bot#9]
Sometimes you need to exchange two different assets that are issued/trusted by the same issuing address. 
I can't manage to set this scenario on the exchange pair.

**Comment by ety001** [comment]
This place has an logic error. I'll fix it in some time. Thank you for your report.

**Comment by skraba** [comment]
Thank you!
BTW great product!

**Comment by ety001** [comment]
@skraba This bug has been fixed. Please refresh your browser and check the version. The version is v0.0.9 now.
